# Generated by Django 4.0.4 on 2022-05-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='availabiltiy',
        ),
        migrations.AddField(
            model_name='part',
            name='isAvailable',
            field=models.BooleanField(default=False),
        ),
    ]
